### ISSUE TITLE
Error during fine-tuning: "cannot reshape array of size 1 into shape (2)"

### ISSUE THREAD

**Issue by HanboYangC** [davidbuterez/multi-fidelity-gnns-for-drug-discovery#1]
Hi, thanks for your work! I tried to run your finetune code with the script you provide in 'Pre-train on low-fidelity and fine-tune on high-fidelity' part. Specifically, it looks like this

```
python -m multifidelity_gnn.train.train_fine_tune_high_fidelity --high-fidelity-data-path example_data/DR --high-fidelity-label DR \
--node-latent-dim 50 --graph-latent-dim 256 --out-dir example_data/out_finetune --smiles-column neut-smiles --max-atomic-number 53 \
--max-num-atoms-in-mol 124 --readout set_transformer --id-column CID --use-vgae --num-layers 3 --conv GCN --use-batch-norm \
--gnn-intermediate-dim 256 --use-cuda --logging-name Finetune --batch-size 512 --dataloader-num-workers 12 \
--set-transformer-hidden-dim 1024 --set-transformer-num-heads 16 --set-transformer-num-sabs 2 --set-transformer-dropout 0.0 \
--low-fidelity-ckpt-path 'example_data/out_LF_models/epoch=001-train_total_loss=1.85941.ckpt' --freeze-vgae
```

Besides, you could find I deleted the argument '--num-epochs' because the script doesn't recognize this argument with error
`train_fine_tune_high_fidelity.py: error: unrecognized arguments: --num-epochs 1`

However , when I tried to run the script above, it gives error
```Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "~/DrugScreening1/GNN/multifidelity_gnn/train/train_fine_tune_high_fidelity.py", line 209, in <module>
    main()
  File "~/DrugScreening1/GNN/multifidelity_gnn/train/train_fine_tune_high_fidelity.py", line 200, in main
    trainer.fit(model, data_module)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "~/.conda/envs/GNN/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "~/DrugScreening1/GNN/multifidelity_gnn/src/data_loading.py", line 73, in __getitem__
    labels = torch.Tensor(self.scaler.transform(targets.reshape(-1, num_tasks)))
ValueError: cannot reshape array of size 1 into shape (2)
```
Any help would be greatly appreciated. Thank you!

**Comment by davidbuterez** [comment]
Hi, thanks for pointing out this issue!

First of all, regarding `--num-epochs`, the fine-tuning code uses an early stopping callback to detect when to stop training and the number of epochs should not be fixed. I now see that this argument was still included in the demo code, so now I have removed it.

Regarding the main error, there was indeed a bug in the code. Technically, multiple target column names can be passed as a list, although I always used only 1. `num_tasks` was incorrectly set when a string (not list) was passed.

These problems should be fixed in 2d65e0f994e978071c9e5419488323f34560b572. I hope this helps!
